site_name: "Currículum - Vanderli Marques dos Reis"
site_url: https://vanderlitecnologia.github.io/vanderli-curriculum/

theme:
  name: material
  custom_dir: overrides
  language: pt-BR
  palette:
    - scheme: default
      primary: blue
      accent: blue
  features:
    - navigation.top
    - toc.integrate
  generator: false
    
markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.highlight

plugins:
  - search

nav:
  - Currículum: index.md

